[package]
name = "planets"
version = "0.1.0"
authors = ["nurmieem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.21.0"
nalgebra = "0.18.1"
rand = "0.7.2"