[package]
name = "planets"
version = "0.1.0"
authors = ["Tuupertunut"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30.0"
nalgebra = "0.25.4"
rand = "0.8.2"
